;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-case-fold-search nil)
 '(ahs-default-range (quote ahs-range-whole-buffer))
 '(ahs-idle-interval 0.25)
 '(ahs-idle-timer 0 t)
 '(ahs-inhibit-face-list nil)
 '(beacon-blink-delay 0.3)
 '(cfs--current-profile-name "profile1" t)
 '(company-dabbrev-minimum-length 3)
 '(company-dabbrev-other-buffers nil)
 '(company-show-numbers t)
 '(company-statistics-auto-restore nil)
 '(ctags-update-delay-seconds 1024)
 '(erc-nick "zilongshanren")
 '(erc-port 6666)
 '(evil-want-C-i-jump t)
 '(exec-path-from-shell-arguments (quote ("-l")))
 '(expand-region-contract-fast-key "V")
 '(expand-region-exclude-text-mode-expansions (quote (html-mode nxml-mode web-mode)))
 '(expand-region-reset-fast-key "r")
 '(flycheck-display-errors-delay 0.4)
 '(global-command-log-mode nil)
 '(global-highlight-parentheses-mode nil)
 '(golden-ratio-exclude-modes
   (quote
    ("bs-mode" "calc-mode" "ediff-mode" "dired-mode" "gud-mode" "gdb-locals-mode" "gdb-registers-mode" "gdb-breakpoints-mode" "gdb-threads-mode" "gdb-frames-mode" "gdb-inferior-io-mode" "gud-mode" "gdb-inferior-io-mode" "gdb-disassembly-mode" "gdb-memory-mode" "restclient-mode" "speedbar-mode" term-mode)))
 '(helm-ag-always-set-extra-option nil)
 '(helm-gtags-update-interval-second 35)
 '(helm-ls-git-fuzzy-match t)
 '(helm-ls-git-show-abs-or-relative (quote absolute))
 '(hl-paren-background-colors nil)
 '(hl-paren-colors nil)
 '(hl-paren-delay 0.5)
 '(ivy-height 18)
 '(linum-eager nil)
 '(lua-documentation-url "http://www.lua.org/manual/5.3/manual.html")
 '(magit-use-overlays nil)
 '(org-agenda-custom-commands nil)
 '(org-agenda-ndays 1)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-deadline-prewarning-if-scheduled t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-agenda-text-search-extra-files (quote (agenda-archives)))
 '(org-deadline-warning-days 14)
 '(org-fast-tag-selection-single-key (quote expert))
 '(org-log-into-drawer t)
 '(org-pomodoro-play-sounds nil)
 '(org-reverse-note-order t)
 '(package-selected-packages
   (quote
    (edn paredit queue peg json-rpc dash-functional web-completion-data makey anzu highlight goto-chg flx gh logito pcache pos-tip guide-key request parent-mode simple-httpd json-snatcher json-reformat multiple-cursors moz ctable orglue epic alert log4e gntp spinner epl hydra async deferred f s chinese-word-at-point dash youdao-dictionary ws-butler window-numbering web-mode web-beautify volatile-highlights vi-tilde-fringe use-package tagedit smooth-scrolling slim-mode scss-mode sass-mode rfringe reveal-in-finder rainbow-mode rainbow-identifiers rainbow-delimiters pyvenv pyenv-mode popwin pip-requirements persp-projectile pbcopy page-break-lines ox-reveal org-repo-todo org-present org-octopress org-mac-link org-download org-bullets open-junk-file neotree multi-term moz-controller move-text monokai-theme markdown-toc magit macrostep lispy linum-relative leuven-theme less-css-mode json-mode js2-refactor js-doc indent-guide impatient-mode ido-vertical-mode hungry-delete hl-anything highlight-parentheses highlight-numbers highlight-indentation helm-themes helm-swoop helm-pydoc helm-projectile helm-mode-manager helm-make helm-ls-git helm-gtags helm-gitignore helm-github-stars helm-flyspell helm-descbinds helm-css-scss helm-c-yasnippet helm-ag guide-key-tip google-translate golden-ratio github-browse-file gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gist gh-md ggtags geiser fringe-helper flycheck-ycmd flycheck-pos-tip flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-tutor evil-terminal-cursor-changer evil-surround evil-search-highlight-persist evil-org evil-numbers evil-nerd-commenter evil-matchit evil-lisp-state evil-jumper evil-indent-textobject evil-iedit-state evil-exchange evil-args evil-anzu engine-mode emmet-mode elisp-slime-nav elfeed discover-my-major deft dash-at-point cython-mode company-ycmd company-web company-tern company-statistics company-quickhelp company-c-headers company-anaconda command-log-mode coffee-mode cmake-font-lock clj-refactor clean-aindent-mode clang-format cider-eval-sexp-fu chinese-fonts-setup buffer-move auto-yasnippet auto-highlight-symbol auto-dictionary align-cljlet aggressive-indent adaptive-wrap ace-jump-mode ac-ispell 2048-game)))
 '(paradox-github-token t)
 '(pyim-dicts
   (quote
    ((:name "BigDict-01" :file "/Users/guanghui/.emacs.d/pyim/dicts/pyim-bigdict.pyim" :coding utf-8-unix)
     (:name "BigDict-01" :file "/Users/guanghui/.emacs.d/.cache/pyim-bigdict.pyim" :coding utf-8-unix))))
 '(require-final-newline nil)
 '(ring-bell-function (quote ignore) t)
 '(safe-local-variable-values
   (quote
    ((eval setenv "PYTHONPATH" "/Users/guanghui/cocos2d-x/tools/cocos2d-console/plugins:/Users/guanghui/cocos2d-x/tools/cocos2d-console/bin"))))
 '(sp-show-pair-from-inside t)
 '(tags-add-tables nil)
 '(tags-revert-without-query t)
 '(vc-follow-symlinks t)
 '(web-mode-markup-indent-offset 2)
 '(ycmd-extra-conf-handler (quote load))
 '(ycmd-extra-conf-whitelist (quote ("~/cocos2d-x/*"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-definition-face ((t (:foreground "gainsboro" :slant normal))))
 '(ahs-face ((t (:underline "dark gray"))))
 '(ahs-plugin-bod-face ((t nil)))
 '(ahs-plugin-defalt-face ((t (:underline t))))
 '(ahs-plugin-whole-buffer-face ((t (:underline t))))
 '(comint-highlight-input ((t (:foreground "gold" :weight bold))))
 '(company-echo-common ((t (:foreground "salmon"))))
 '(company-preview ((t (:foreground "wheat"))))
 '(company-preview-common ((t (:foreground "light sea green"))))
 '(company-preview-search ((t (:inherit company-preview :background "dark olive green"))))
 '(company-scrollbar-bg ((t nil)))
 '(company-scrollbar-fg ((t (:background "light sea green"))))
 '(company-template-field ((t (:foreground "black"))))
 '(company-tooltip ((t (:background "gray28"))))
 '(company-tooltip-annotation ((t (:inherit company-tooltip :foreground "dark sea green"))))
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil))))
 '(company-tooltip-search ((t (:foreground "forest green" :weight bold))))
 '(company-tooltip-selection ((t (:background "dark olive green" :foreground "light gray"))))
 '(evil-search-highlight-persist-highlight-face ((t (:background "light blue" :foreground "dim gray"))))
 '(flycheck-error ((t (:background "OrangeRed3" :foreground "cornsilk" :underline (:color "orange red" :style wave)))))
 '(flycheck-fringe-error ((t (:foreground "orange red" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "gold" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "gray38"))))
 '(fringe ((t (:background "#334452" :foreground "#ffffff"))))
 '(git-gutter-fr:added ((t (:foreground "#859900" :weight bold :width extra-expanded))))
 '(helm-action ((t (:foreground "orange" :underline t))))
 '(helm-ff-directory ((t (:foreground "light sea green"))))
 '(helm-ff-dotted-directory ((t (:foreground "dim gray"))))
 '(helm-ff-executable ((t (:foreground "light gray" :slant italic))))
 '(helm-ff-file ((t (:foreground "gainsboro"))))
 '(helm-ff-prefix ((t (:background "light sea green" :foreground "aquamarine"))))
 '(helm-header ((t (:background "slate gray" :foreground "light sky blue"))))
 '(helm-header-line-left-margin ((t (:background "olive drab" :foreground "gainsboro"))))
 '(helm-ls-git-modified-and-staged-face ((t (:foreground "dark cyan"))))
 '(helm-ls-git-modified-not-staged-face ((t (:foreground "dark cyan"))))
 '(helm-ls-git-renamed-modified-face ((t (:foreground "dark cyan"))))
 '(helm-match ((t (:background "dim gray" :foreground "lemon chiffon"))))
 '(helm-match-item ((t (:foreground "gold"))))
 '(helm-selection ((t (:underline t))))
 '(helm-separator ((t (:foreground "aquamarine"))))
 '(helm-source-header ((t (:foreground "dim gray"))))
 '(helm-swoop-target-line-face ((t (:underline t))))
 '(helm-swoop-target-word-face ((t (:background "gray26" :foreground "moccasin"))))
 '(helm-visible-mark ((t (:background "CadetBlue4" :foreground "light gray"))))
 '(hl-line ((t (:background "#343D46"))))
 '(hl-paren-face ((t nil)) t)
 '(ido-vertical-match-face ((t (:inherit font-lock-variable-name-face :underline t))))
 '(iedit-occurrence ((t (:inherit cursor))))
 '(ivy-current-match ((t (:underline t))))
 '(ivy-minibuffer-match-face-1 ((t (:foreground "lemon chiffon"))))
 '(js2-error ((t (:foreground "light sea green"))))
 '(js2-external-variable ((t (:foreground "gray52"))))
 '(link ((t (:underline t))))
 '(linum ((t (:background "#334452" :foreground "#65737e"))))
 '(magit-blame-date ((t (:background "#404040" :foreground "dim gray"))))
 '(magit-blame-name ((t (:background "gray31" :foreground "pale violet red"))))
 '(magit-blame-summary ((t (:inherit magit-blame-heading :foreground "dark gray"))))
 '(minibuffer-prompt ((t (:foreground "aquamarine"))))
 '(org-level-1 ((t (:foreground "light goldenrod"))))
 '(org-level-2 ((t (:foreground "yellow green"))))
 '(org-link ((t (:inherit link :foreground "turquoise"))))
 '(sp-pair-overlay-face ((t nil)))
 '(sp-show-pair-match-face ((t (:foreground "deep sky blue" :weight normal))))
 '(sp-wrap-overlay-opening-pair ((t (:foreground "cyan"))))
 '(speedbar-highlight-face ((t nil)))
 '(vimish-fold-overlay ((t (:foreground "dark gray" :box (:line-width 2 :color "LightSkyBlue4")))))
 '(vr/match-separator-face ((t (:foreground "red"))))
 '(web-mode-constant-face ((t (:inherit font-lock-constant-face :foreground "tomato" :slant italic))))
 '(web-mode-function-call-face ((t (:inherit font-lock-function-name-face :foreground "cadet blue" :slant oblique))))
 '(web-mode-html-attr-name-face ((t (:foreground "dark gray"))))
 '(web-mode-html-tag-bracket-face ((t (:foreground "SteelBlue2"))))
 '(web-mode-html-tag-face ((t (:foreground "SteelBlue2"))))
 '(web-mode-variable-name-face ((t (:foreground "LightSkyBlue3")))))
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
